### ISSUE TITLE
How to cancat data with processhtml?

### ISSUE THREAD

**Issue by misterion** [Wildhoney/gulp-processhtml#17]
So, using something like this 

       
       <script src="app.js"></script>
       <script src="module1.js"></script>
       <script src="module2.js"></script>
       

You achieve nice replacement in your template file. How to cancat files to `app.min.js` based on template script data?

**Comment by Wildhoney** [comment]
It isn't the responsibility of `gulp-processhtml` to manipulate files &ndash; it's only concerned with a find-replace of content in HTML documents.

In your case you'll need to setup a Gulp/Grunt file with [`gulp-concat`](https://www.npmjs.com/package/gulp-concat)/[`grunt-contrib-concat`](https://github.com/gruntjs/grunt-contrib-concat). You can see an example with Gulp [here](https://github.com/Wildhoney/earlytwenties.co.uk/blob/master/gulpfile.js#L67).

Essentially all your concatentated and minified files will reside in a deterministic location, which `gulp-processhtml` merely references.

This is great because it allows you to have separate HTML documents for development/production, although the uses are endless. You can also take a look at [sourcemaps](http://www.html5rocks.com/en/tutorials/developertools/sourcemaps/) for debugging minified files on production.

**Comment by misterion** [comment]
Tnx for answer Adam. I do not understand something, apparently. I need to copy-paste js/css file names from html template script/link to separate gulp task to concat them? So i can`t have just on list of files? 
In your sample you concat `earlytwenties.js` and actualy have 2 file lists - one in gulp file and one in html. Is it right?

**Comment by Wildhoney** [comment]
Yep, in the case of the EarlyTwenties project, I have a list of the JS and CSS files that I use for development, so I can modify them with ease and debug too. I then also have a list of the files in my Gulpfile for taking all of those files and generating two files: `earlytwenties.js`/`earlytwenties.css`. With `gulp-processhtml` I can reference those two concatenated files knowing that my Gulpfile.js [will place them where I expect them](https://github.com/Wildhoney/earlytwenties.co.uk/blob/master/gulpfile.js#L21) with `gulp-concat`.

**Comment by Wildhoney** [comment]
I've [added an example](https://github.com/Wildhoney/gulp-processhtml/tree/master/example) for the Gulpfile :+1: Hopefully this helps.

**Comment by misterion** [comment]
Tnx a lot, Adam. I understand that, I just think it's weird. In our project, roughly speaking, we build the output css/js file based on what is written in html. So in dev you can write anything you want and get result. And in production builder get all files to concat from template and concat them. Now, I realize that the world of gulp this information will need to be duplicated.

**Comment by Wildhoney** [comment]
Not necessarily! In your Gulpfile you could parse out the list of files from your `index.html`. Although this isn't something that `gulp-processhtml` would concern itself with &ndash; although I'm happy to be corrected on this if people think it should be a responsibility of the module.

It isn't perfect as it'll match every `script` file regardless of the `gulp-processhtml` boundaries, but it's a start:

**Gulpfile**:

```javascript
var indexPage = require('fs').readFileSync('index.html', 'utf-8');
var files     = indexPage.match(/src=".+?"/ig).map(function(matched) {
    return matched.match(/src="(.+?)"/i)[1];
});

console.log(files);
```

**Comment by misterion** [comment]
Is it any way to be a part of replacement process during `gulp-processhtml` execution? Some filter with signature like this 

     function(targetFileName, currentFilePath, rawHtmlOfSegment) {
     }

So the user can make any additional steps having this information. Match and map for example and pass data to `gulp-concat`.

**Comment by Wildhoney** [comment]
In `node-htmlprocessor` (which `gulp-processhtml` delegates to) there is [a `--list` option](https://github.com/dciccale/node-htmlprocessor#new-option) which allows you to output a file which enumerates all of the replaced files.

With that file you can modify your Gulpfile to something like the following to parse that file:

```javascript
gulp.task('replacements', ['processhtml'], function() {

    var fileList = require('fs').readFileSync('replacements.list', 'utf8');
    var files    = fileList.match(/:.+/ig).map(function(matched) {
        return matched.replace(/:/, '');
    });

    console.log(files);

});
```

And then afterwards to remove the **replacements.list** file using [`gulp-rimraf`](https://github.com/robrich/gulp-rimraf).

**Comment by misterion** [comment]
Awesome! Tnx!
