### ISSUE TITLE
Cannot include some files

### ISSUE THREAD

**Issue by mcmimik** [Wildhoney/gulp-processhtml#18]
I've upload my project here: https://github.com/mcmimik/Test-for-processhtml-bug

There is one file with multiple included templates (.htm), that include other files (.svg).
The result is: https://monosnap.com/file/3yokG0sxmPkevKudXMTsZkbvTmaWdN

I've spent plenty hours to figure out what's wrong, but it's not clear for me. Could you please help me?

**Comment by Wildhoney** [comment]
That seems peculiar &mdash; could you try raising the issue on [`node-htmlprocessor`](https://github.com/dciccale/node-htmlprocessor/issues) and mention that you use this Gulp plugin. I have a suspicion this bug lies in the Node implementation, which is a dependency.

**Comment by mcmimik** [comment]
Thank you! I've created an issue there: https://github.com/dciccale/node-htmlprocessor/issues/19

**Comment by Wildhoney** [comment]
I've just cloned your project and ran it myself with `gulp html` &mdash; I seem to be getting better results than you:

[Screenshot](http://i.imgur.com/XQeXX0Z.png)

**Comment by mcmimik** [comment]
I've made the same once more and got this error again. How can I log this process to give you more information about my case?

**Comment by Wildhoney** [comment]
I don't understand what could be happening. I would highly doubt that it comes to a difference in OS, for example, because the Node module for processing HTML files is quite simple.

Could you try and use the module [directly using the CLI](https://github.com/dciccale/node-htmlprocessor#cli)?

```
htmlprocessor src/index.html -o build/index.html
```

**Comment by Wildhoney** [comment]
For me:

![Screenshot](http://i.imgur.com/Nrx5pFG.png)

**Comment by dciccale** [comment]
@Wildhoney you need to pass the `--recursive` option if you run directly from the CLI

**Comment by Wildhoney** [comment]
:+1: Realised after I'd posted.

**Comment by dciccale** [comment]
the issue in the processor repo https://github.com/dciccale/node-htmlprocessor/issues/19 was closed until further analysis.

we should close this one anyway, since if there *is* an issue would be in the processor and not in the plugin.
